export const SITE_NAME = 'Lookout';
// Static demo dashboard, generated by `cmd/lookout-demo` into ./docs and shipped
// as the site's public/demo/ (served at <base>/demo/). Base-aware like CONTACT_HREF.
export const DEMO_URL = `${import.meta.env.BASE_URL.replace(/\/?$/, '/')}demo/`;
// Internal route to the contact page (relative to the site base, e.g. "/contact/").
export const CONTACT_HREF = `${import.meta.env.BASE_URL.replace(/\/?$/, '/')}contact/`;
export const TAGLINE = 'IT infrastructure monitoring built for humans.';
